### PR TITLE
StandardCyborgUI: fix file reference

### PR DESCRIPTION
**Pull request by jeffchuber**
StandardCyborgUI/StandardCyborgUI.xcodeproj/project.pbxproj still referenced `PointCloudPreviewViewController.swift` and `PointCloudPreviewViewController.scn` even though we switched to `ScenePreviewViewController.swift`, and `ScenePreviewViewController.scn`. This PR fixes it.

### CODE REVIEW

**Comment by theDiegoJRR** [comment]
Has there been any changes on this? I'm getting an error when trying to save a scan, and it's related to the ScenePreviewViewController class, I'm guessing this is the reason

**Comment by jeffchuber** [comment]
@theDiegoJRR does this PR work for you?

**Comment by wikyburns** [comment]
HI @jeffchuber I was trying to save to obj file, but on it doesn't entries on the if cause the first let was false(let previewVC = presentedViewController as? ScenePreviewViewController)


there's my code, any ideas?

`@objc private func previewSaveTapped(_ sender: UIButton)
    {
        
        if
            let previewVC = presentedViewController as? ScenePreviewViewController
            ,
            let documentsURL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first
        {
            
            let objURL = documentsURL.appendingPathComponent("Scan.obj")
            let thumbnailURL = documentsURL.appendingPathComponent("Scan.jpeg")
            previewVC.scScene.pointCloud?.writeToOBJ(atPath: objURL.path)

            // Guardar jpeg
            if let image = UIImage(named: "Scan.jpeg") {
                if let data = image.jpegData(compressionQuality: 0.8){
                    let filename = thumbnailURL
                    try? data.write(to: filename)
                    print(filename)
                }
            }
        }
        
        dismiss(animated: false)
    }
`

**Comment by saamerm** [comment]
@jeffchuber the new GLTF files generated don't seem to work with a lot of tools. We can't event convert the file to PLY
You can see the error if you try to view any StandardCybord generated GLTF file in popular online viewers like:
https://gltf-viewer.donmccurdy.com 
It gives this error: `null is not an object (evaluating 'i.length')`

Here's a [test file](https://drive.google.com/file/d/14qEoLa2ZRmKVj8_JMVi0yQ3IANA3CQRC/) you can use, or I can share the file in a GIST if you prefer

Is there someone I can discuss about this issue?

**Comment by aaptho** [comment]
> @jeffchuber the new GLTF files generated don't seem to work with a lot of tools. We can't event convert the file to PLY You can see the error if you try to view any StandardCybord generated GLTF file in popular online viewers like: https://gltf-viewer.donmccurdy.com It gives this error: `null is not an object (evaluating 'i.length')`
> 
> Here's a [test file](https://drive.google.com/file/d/14qEoLa2ZRmKVj8_JMVi0yQ3IANA3CQRC/) you can use, or I can share the file in a GIST if you prefer
> 
> Is there someone I can discuss about this issue?

@saamerm that sounds like an unrelated error. While Standard Cyborg is now defunct as a corporation, we will be open sourcing the guts soon, and you may be able to fix the GLTF issues yourself.

**Pull request closed without merging**
